import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu } from "@mui/icons-material";
import { Drawer, Typography } from "@mui/joy";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section className="flex items-center px-8 py-4">
        <Menu className="me-2"/>
        <Typography level="h4">JDC PORTAL</Typography>
        </section>
        {children}
      </body>
    </html>
  );
}

function MainLayout({children} : {children:React.ReactNode}){
  return(
    <body>
      <section className="flex items-center px-8 py-4">
        <Menu className="me-2"/>
        <Typography level="h4">JDC PORTAL</Typography>
        </section>
        {children}
    </body>
  )
}
