import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="py-3 px-4 bg-blend-color-burn">
          <div className="flex justify-between">
            <span>Using States</span>

            <ul>
              <li className="px-3">
                <Link href={'/simple'}>Use State</Link>
                <Link href={'/provider'}>Use State Provider</Link>
              </li>
            </ul>
          </div>
        </nav>
        <main className="px-6 py-4">
        {children}
        </main>
      </body>
    </html>
  );
}
